django-elective-todolist/todoapp/urls.py
from django.urls import path
from . import views

app_name = 'todoapp'

urlpatterns = [
    path('details/<int:pk>', views.details, name='details'),
    path('', views.index, name='index'),
]

django-elective-todolist/todoproject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('todo/', include('todoapp.urls'), name='todoapp'),
    path('users/', include('users.urls'), name='usersapp'),
    path('admin/', admin.site.urls),
]

django-elective-todolist/users/urls.py
from django.urls import path

from . import views


app_name = 'usersapp'

urlpatterns = [
    path('', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('signup', views.signup, name='signup'),
    path('password_reset', views.password_reset, name='password_reset'),
]

django-elective-todolist/todoapp/models.py
from django.db import models
from django.contrib.auth.models import User


class TodoItem(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True)
    status = models.BooleanField()

django-elective-todolist/users/models.py
from django.db import models

# Create your models here.

django-elective-todolist/todoapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.urls import reverse
from .models import *


def index(request):
    if request.method == 'GET':
        todo_items = TodoItem.objects.all()
        context = {
            'todos': todo_items
        }
        return render(request, 'todoapp/index.html', context)

    elif request.method == 'POST':
        title, status = request.POST['title'], True if len(request.POST.getlist('status')) > 0 else False
        description = request.POST['description']
        todo_item = TodoItem()
        todo_item.title = title
        todo_item.status = status
        todo_item.description = description
        todo_item.save()
        return HttpResponseRedirect(reverse('todoapp:index'))

    return HttpResponseBadRequest()


def details(request, pk):
    todo_item = get_object_or_404(TodoItem, pk=pk)

    if request.method == 'GET':
        context = {
            'todo': todo_item,
            'pk': pk
        }
        return render(request, 'todoapp/details.html', context)

    elif request.method == 'POST':
        title, status = request.POST['title'], True if len(request.POST.getlist('status')) > 0 else False
        description = request.POST['description']
        todo_item.title = title
        todo_item.status = status
        todo_item.description = description
        todo_item.save()
        return HttpResponseRedirect(reverse('todoapp:index'))

    return HttpResponseBadRequest()

django-elective-todolist/users/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout


def login(request):
    context = {}
    if request.method == 'POST':
        user = authenticate(request,
            username=request.POST['user'],
            password=request.POST['password'])
        if user:
            dj_login(request, user)
            context = {'user':request.POST['user']}
            return HttpResponseRedirect(reverse('todoapp:index'))
        else:
            context = {'error':'Username or password is wrong.'}

    return render(request, 'usersapp/login.html', context)


def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse('usersapp:login'))


def signup(request):
    pass


def password_reset(request):
    pass

django-elective-todolist/todoapp/templates/todoapp/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>To do App</title>
</head>
<body>
    <h1>To Do List - Item Details</h1><br>
    <form action="./{{pk}}" method="POST" id="frmDetails">
        {% csrf_token %}
        Task Title: <input type="text" name="title" placeholder="Task to do" size="50" value="{{todo.title}}"><br>
        Details: <textarea form="frmDetails" name="description" placeholder="Task to do" rows="6" cols="50">{{ todo.description }}</textarea><br>
        Status: <input type="checkbox" name="status" {% if todo.status %}checked{%endif%}><br>
        <button type="submit">Submit Changes</button>
    </form>
</body>
</html>

django-elective-todolist/todoapp/templates/todoapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>To do App</title>
</head>
<body>
    <h1>To Do List</h1>
    <table border="1">
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Completed</th>
        <th>Actions</th>
      </tr>
        {% for item in todos %}
            <tr>
                <th>{{ item.title }}</th>
                <th>{{ item.description }}</th>
                <th>{{ item.status }}</th>
                <th><a href="{% url 'todoapp:details' item.pk %}">Edit</a></th>
            </tr>
        {% endfor %}
    </table><br><hr>
    <h1>Add to the Todo List</h1><br>
    <form action="." method="POST" id="frmAddTask">
        {% csrf_token %}
        Task Title: <input type="text" name="title" placeholder="Task to do"><br>
        Details: <textarea form="frmAddTask" name="description" placeholder="Task to do" rows="6" cols="50">{{ todo.description }}</textarea><br>
        Status: <input type="checkbox" name="status"><br>
        <button type="submit">Submit this task</button>
    </form>
</body>
</html>